"""Stable enums for the BSIP v3.2.0 Claim Engine."""

from __future__ import annotations

from enum import Enum


class ClaimCategory(str, Enum):
    CHEMICAL_DISCRIMINATION = "CHEMICAL_DISCRIMINATION"
    CONCENTRATION_INFORMATION = "CONCENTRATION_INFORMATION"
    TEMPORAL_INFORMATION = "TEMPORAL_INFORMATION"
    FEATURE_REPRESENTATION = "FEATURE_REPRESENTATION"
    STRAIN_CONTRIBUTION = "STRAIN_CONTRIBUTION"
    DATA_QUALITY = "DATA_QUALITY"
    GENERALIZATION = "GENERALIZATION"
    SYSTEM_LEVEL_PERFORMANCE = "SYSTEM_LEVEL_PERFORMANCE"


class ClaimType(str, Enum):
    PRIMARY_FINDING = "PRIMARY_FINDING"
    SUPPORTING_FINDING = "SUPPORTING_FINDING"
    CONTEXTUAL_FINDING = "CONTEXTUAL_FINDING"
    LIMITATION = "LIMITATION"
    WITHHELD = "WITHHELD"


class ClaimStatus(str, Enum):
    SUPPORTED = "SUPPORTED"
    PARTIALLY_SUPPORTED = "PARTIALLY_SUPPORTED"
    TENTATIVE = "TENTATIVE"
    CONFLICTED = "CONFLICTED"
    WITHHELD = "WITHHELD"
    NOT_ASSESSABLE = "NOT_ASSESSABLE"


class EvidenceStrength(str, Enum):
    STRONG = "STRONG"
    MODERATE = "MODERATE"
    LIMITED = "LIMITED"
    INSUFFICIENT = "INSUFFICIENT"
    NOT_ASSESSABLE = "NOT_ASSESSABLE"


class PublicationUse(str, Enum):
    RESULTS_ELIGIBLE = "RESULTS_ELIGIBLE"
    DISCUSSION_ELIGIBLE = "DISCUSSION_ELIGIBLE"
    LIMITATION_ONLY = "LIMITATION_ONLY"
    INTERNAL_REVIEW_ONLY = "INTERNAL_REVIEW_ONLY"
    NOT_ELIGIBLE = "NOT_ELIGIBLE"


class ConfidenceLabel(str, Enum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    NOT_ASSESSABLE = "NOT_ASSESSABLE"


class ClaimIssueSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


def category_id_token(category: ClaimCategory | str) -> str:
    return ClaimCategory(category).value
