"""Enums for the BSIP v4.0.0 Evidence Scoring Engine."""

from __future__ import annotations

from enum import Enum


class EvidenceDimension(str, Enum):
    TRACEABILITY = "TRACEABILITY"
    SOURCE_VALIDATION = "SOURCE_VALIDATION"
    OBSERVATION_SUPPORT = "OBSERVATION_SUPPORT"
    INTERPRETATION_SUPPORT = "INTERPRETATION_SUPPORT"
    HYPOTHESIS_SUPPORT = "HYPOTHESIS_SUPPORT"
    COMPETING_HYPOTHESIS_CONTROL = "COMPETING_HYPOTHESIS_CONTROL"
    EVIDENCE_GAP_BURDEN = "EVIDENCE_GAP_BURDEN"
    LIMITATION_COMPLETENESS = "LIMITATION_COMPLETENESS"
    INTERNAL_CONSISTENCY = "INTERNAL_CONSISTENCY"
    GENERALIZATION_SUPPORT = "GENERALIZATION_SUPPORT"
    REPRODUCIBILITY_SUPPORT = "REPRODUCIBILITY_SUPPORT"
    OVERALL_ROBUSTNESS = "OVERALL_ROBUSTNESS"


class EvidenceLevel(str, Enum):
    INSUFFICIENT = "INSUFFICIENT"
    LIMITED = "LIMITED"
    MODERATE = "MODERATE"
    STRONG = "STRONG"
    VERY_STRONG = "VERY_STRONG"


class PublicationReadiness(str, Enum):
    NOT_READY = "NOT_READY"
    LIMITATION_ONLY = "LIMITATION_ONLY"
    DISCUSSION_READY = "DISCUSSION_READY"
    RESULTS_READY = "RESULTS_READY"
    HIGH_CONFIDENCE_RESULTS_READY = "HIGH_CONFIDENCE_RESULTS_READY"


class UncertaintyLevel(str, Enum):
    VERY_HIGH = "VERY_HIGH"
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    VERY_LOW = "VERY_LOW"


class ReviewerConfidence(str, Enum):
    LOW = "LOW"
    GUARDED = "GUARDED"
    MODERATE = "MODERATE"
    HIGH = "HIGH"


class EvidenceScoringIssueSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
