"""Stable enums for the BSIP v4.1.0 Reviewer Engine."""

from __future__ import annotations

from enum import Enum


class ReviewerType(str, Enum):
    SCIENTIFIC = "SCIENTIFIC"
    STATISTICAL = "STATISTICAL"
    EVIDENCE = "EVIDENCE"
    VALIDATION = "VALIDATION"
    REPRODUCIBILITY = "REPRODUCIBILITY"
    FIGURE = "FIGURE"
    WRITING = "WRITING"
    PUBLICATION = "PUBLICATION"


class ReviewCategory(str, Enum):
    CLAIM_SUPPORT = "CLAIM_SUPPORT"
    GENERALIZATION = "GENERALIZATION"
    DATA_QUALITY = "DATA_QUALITY"
    STATISTICAL_INTERPRETATION = "STATISTICAL_INTERPRETATION"
    COMPETING_EXPLANATIONS = "COMPETING_EXPLANATIONS"
    EXTERNAL_VALIDATION = "EXTERNAL_VALIDATION"
    TRACEABILITY = "TRACEABILITY"
    REPRODUCIBILITY = "REPRODUCIBILITY"
    FIGURE_SUPPORT = "FIGURE_SUPPORT"
    TABLE_SUPPORT = "TABLE_SUPPORT"
    LANGUAGE_STRENGTH = "LANGUAGE_STRENGTH"
    PUBLICATION_READINESS = "PUBLICATION_READINESS"
    LIMITATION_COMPLETENESS = "LIMITATION_COMPLETENESS"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"


class Severity(str, Enum):
    CRITICAL = "CRITICAL"
    MAJOR = "MAJOR"
    MODERATE = "MODERATE"
    MINOR = "MINOR"
    INFORMATION = "INFORMATION"


class ReviewerConfidence(str, Enum):
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    GUARDED = "GUARDED"
    LOW = "LOW"


class PublicationRisk(str, Enum):
    BLOCKING = "BLOCKING"
    HIGH = "HIGH"
    MODERATE = "MODERATE"
    LOW = "LOW"
    NONE = "NONE"


class OverallRecommendation(str, Enum):
    INTERNAL_REVIEW_ONLY = "INTERNAL_REVIEW_ONLY"
    NEEDS_MAJOR_REVISION = "NEEDS_MAJOR_REVISION"
    NEEDS_MODERATE_REVISION = "NEEDS_MODERATE_REVISION"
    NEEDS_MINOR_REVISION = "NEEDS_MINOR_REVISION"
    READY_FOR_DRAFT_MANUSCRIPT = "READY_FOR_DRAFT_MANUSCRIPT"


class ReviewIssueSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
