"""Stable enums for the BSIP v4.2.0 Manuscript Engine."""

from __future__ import annotations

from enum import Enum


class DocumentStatus(str, Enum):
    INTERNAL_DRAFT = "INTERNAL_DRAFT"
    SUPERVISOR_REVIEW_DRAFT = "SUPERVISOR_REVIEW_DRAFT"
    REVISION_REQUIRED = "REVISION_REQUIRED"
    NOT_GENERATED = "NOT_GENERATED"


class SectionType(str, Enum):
    TITLE = "TITLE"
    ABSTRACT_PLACEHOLDER = "ABSTRACT_PLACEHOLDER"
    INTRODUCTION_PLACEHOLDER = "INTRODUCTION_PLACEHOLDER"
    METHODS_PLACEHOLDER = "METHODS_PLACEHOLDER"
    RESULTS = "RESULTS"
    DISCUSSION = "DISCUSSION"
    LIMITATIONS = "LIMITATIONS"
    CONCLUSION = "CONCLUSION"
    FIGURE_CAPTIONS = "FIGURE_CAPTIONS"
    TABLE_CAPTIONS = "TABLE_CAPTIONS"
    REVISION_NOTES = "REVISION_NOTES"


class SentenceType(str, Enum):
    RESULT = "RESULT"
    INTERPRETATION = "INTERPRETATION"
    LIMITATION = "LIMITATION"
    CONTEXT = "CONTEXT"
    CONCLUSION = "CONCLUSION"
    FIGURE_REFERENCE = "FIGURE_REFERENCE"
    TABLE_REFERENCE = "TABLE_REFERENCE"


class SentenceStatus(str, Enum):
    ALLOWED = "ALLOWED"
    QUALIFIED = "QUALIFIED"
    RESTRICTED = "RESTRICTED"
    WITHHELD = "WITHHELD"


class PublicationBoundary(str, Enum):
    RESULTS_ALLOWED = "RESULTS_ALLOWED"
    DISCUSSION_ONLY = "DISCUSSION_ONLY"
    LIMITATION_ONLY = "LIMITATION_ONLY"
    INTERNAL_ONLY = "INTERNAL_ONLY"
    WITHHELD = "WITHHELD"


class TraceabilityStatus(str, Enum):
    COMPLETE = "COMPLETE"
    PARTIAL = "PARTIAL"
    MISSING = "MISSING"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ResolutionStatus(str, Enum):
    APPLIED_AS_QUALIFICATION = "APPLIED_AS_QUALIFICATION"
    MOVED_TO_DISCUSSION = "MOVED_TO_DISCUSSION"
    MOVED_TO_LIMITATIONS = "MOVED_TO_LIMITATIONS"
    WITHHELD = "WITHHELD"
    REQUIRES_AUTHOR_ACTION = "REQUIRES_AUTHOR_ACTION"
    NOT_APPLICABLE = "NOT_APPLICABLE"


class ManuscriptIssueSeverity(str, Enum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
